datasets:
  repo_name: "LilyYang0504/BenchDatasets"
  local_dir: "./datasets"

model:
  name: "E:/test_down/Qwen-VL-235B-A22B-Instruct_0001/snapshots/7d7bd7bcc35b77b391883ebd7f9686cfa0e25cc0"
  alias: "OpenGVLab/InternVL3_5-2B"
  device: "cuda"
  torch_dtype: "bfloat16"
  use_flash_attn: true
  trust_remote_code: true
  cache_dir: null
  

task:
  type: "qa"  # all, qa, mask
  max_frames: null
  limit: null

evaluation:
  boundary_threshold: 2

output:
  results_dir: "./results"
  save_details: true
  save_masks: true 